QualityUnit/hugo-boilerplate

content/internal/design-system/_index.md, layouts/_default/design-system.html, layouts/partials/design-system/colors.html, layouts/partials/design-system/css-variables.html, layouts/partials/design-system/gradients.html, layouts/partials/design-system/typography.html, layouts/partials/head.html, layouts/partials/head/variables.html, tailwind.config.js
- I added default variables colors for theme which we know rewrite per project. In project we need only change colors in hugo config file hugo.toml
- I added pages for design system. You can check it `/internal/design-system/` - page is no-indexed and private. Then we can adding list for components, sections.
=> Added support for variables styles

layouts/partials/sections/pricing/base.html, layouts/shortcodes/pricing-base.html
Set columns variable for dynamic change in partial (default 4 tiers), changed name of files (base file for pricing), changed styles elements (buttons, labels) for pricing base on LA and Tailwind pricing section.
Go to pricing page and check pricing section
Close https://github.com/QualityUnit/web-issues/issues/3412
=> [3412] - pricing fix tables

layouts/partials/components/tooltip/tooltip.html, layouts/partials/sections/pricing/with_comparison_table.html, layouts/shortcodes/pricing-with-comparison-table.html
Changed comparison pricing table, added default data (from LA)
Created shortcode for this pricing component
Added annual/monthly toggle
Changed styles base on LA design (4 columns)
To check:
- Go to pricing page and check "Compare plans" section
=> [3412] - pricing comparison table

i18n/en.yaml, layouts/partials/components/tooltip/tooltip.html, layouts/partials/sections/pricing/base.html, layouts/partials/sections/pricing/with_comparison_table.html, layouts/shortcodes/pricing-base.html, layouts/shortcodes/pricing-with-comparison-table.html
Updated lang phrases in partial pricing, remove default values in partials, changed icons to new from /partials/icons
After merge need add content variables inside pricing.md for "pricing-with-comparison-table" shortcode
=> fix: updated lang, remove default values in partials, changed icons

layouts/partials/components/tooltip/tooltip.html
Refactor tooltip component for improved mobile functionality and position handling
=> fix: changed tooltip component

layouts/_default/landing-page.html, layouts/partials/sections/bentogrids/three_column_bento_grid.html, layouts/partials/sections/bentogrids/two_row_bento_grid.html, layouts/partials/sections/features/simple_three_column_with_large_icons.html, layouts/partials/sections/features/with_split_image.html, layouts/shortcodes/bentogrid-three-column.html, layouts/shortcodes/bentogrid-two-row.html, layouts/shortcodes/features-with-split-image.html
Updated partials and shortcodes (default values, color primary, added additional varaibles - description, link for two_row_bento_grid partial) for Product pages
=> [3436] - feat: updated partials and shortcodes

layouts/partials/sections/features/with_alternating_sections.html, layouts/shortcodes/features-with-alternating-sections.html
Add optional parameters for features-with-alternating-section shortcode
=> [3437] - Add optional parameters for features-with-alternating-section

layouts/partials/sections/pricing/with_comparison_table.html, layouts/shortcodes/pricing-with-comparison-table.html
added conditions as if is value empty dont crate element. 
added global buttons support
=> Reworking of pricing compare table

i18n/en.yaml, layouts/partials/components/media/youtubevideo.html, layouts/partials/sections/banners/with_image.html, layouts/partials/sections/courses/courses-content.html, layouts/partials/sections/courses/courses-video.html, layouts/shortcodes/courses-content.html, layouts/shortcodes/courses-video.html
Created course_content and course_video partials and shortcodes for AI-Training page, changed position for youtube video (was black screen after click). Created new partial banner (with_image)
Realted with https://github.com/QualityUnit/FlowHunt-hugo/pull/24
=> [3446] - ai training

layouts/partials/head/css.html
Now if is custom.css file empty we dont include him
=> fix including custom styles

layouts/partials/sections/contact/split-with-pattern.html
Fixed design of contact form section
=> aded and removed sam classes

layouts/partials/sections/features/with_alternating_sections.html, layouts/partials/sections/features/with_large_screenshot.html, layouts/shortcodes/features-with-large-screenshot.html
Update lazy image classes in feature_with_alternating_sections and enhance screenshot handling in with_large-screenshot partial
Related with https://github.com/QualityUnit/urlslab-hugo/pull/3
=> fix: update lazy image classes and enhance screenshot handling

layouts/partials/sections/content/split_with_image.html, layouts/partials/sections/courses/courses-content.html, layouts/partials/sections/features/with_alternating_sections.html, layouts/shortcodes/features-with-alternating-sections.html
fixing wrappers in partials for ai training page
=> fixing partials for ai training page

layouts/partials/sections/bentogrids/two_row_bento_grid.html
Updated bento-grid-row partial by new design
Related with issue https://github.com/QualityUnit/web-issues/issues/3525
=> [3525] - feat: updated bento-grid-row partial by new design

layouts/partials/components/logos/simple.html
Updated logo order and adjust layout styles in simple.html
Realted issue - https://github.com/QualityUnit/web-issues/issues/3524
=> [3524] - feat: refactor logo order and adjust layout styles in simple.html

layouts/partials/utils/analytics/google-analytics-consent.html
close https://github.com/QualityUnit/web-issues/issues/3554
=> fix GA tracking - domains

README.md, assets/css/main.css, layouts/partials/head.html, layouts/partials/head/css.html, layouts/partials/head/js.html
=> Additionlas changes to last PR with refactoring build process

layouts/partials/sections/bentogrids/three_column_bento_grid.html
Removed hover effect for all card
- Go to home page "Learn more about FlowHunt" section and shouldn't use hover effect for card
=> fix: removed hover effect for all card

layouts/partials/components/label/label.html, layouts/partials/sections/courses/courses-content.html, layouts/shortcodes/courses-content.html
Updated courses-content shortcode and partial with theme support and improved parameter handling, badges and styles by design
- Go to single ai-training page e.g. /services/ai-training/microsoft-365-copilot-essentials/ and check
QualityUnit/web-issues#3523
=> [3523] - fix: updated courses-content shortcode and partial

layouts/partials/sections/features/with_intro_and_tabs.html
Updated styles for title, perex and tabs
- Go to any pages with tabs section e.g. homepage and check styles for title, perex and tabs list
QualityUnit/web-issues#3556
=> [3556] - fix: updated styles for title, perex and tabs

layouts/partials/design-system/partials-layout.html, layouts/partials/layout/headers/simple_with_eyebrow_base.html
Fix name of partials what was changed in other PR
=> replaced correct partial name

layouts/partials/sections/content/split_with_image.html
centeed vertical image and set image to contain
=> Edit the split-with-image partial

layouts/partials/sections/testimonials/grid.html
=> Removed useless class wrapper from testimonial section

layouts/partials/sections/bentogrids/three_column_bento_grid.html, layouts/shortcodes/bentogrid-three-column.html
Added theme parameter from comments and example of shortcode
QualityUnit/web-issues#3601
=> [3601] - bentogrid three column shortocode fix

layouts/partials/related_content.html
Fixed padding for related-content partial
- Go to services pages and scroll to related-content partial and check paddings
QualityUnit/web-issues#3661
=> [3661] - fix: adjust padding for related content section

layouts/partials/layout/headers/simple_with_eyebrow_base.html, layouts/partials/sections/content/three_columns_base.html, layouts/shortcodes/content-three-column.html
Created content-three-column shortcode and partial for photomatic-ai section "Photo Showcase", updated layouts/partials/layout/headers/simple_with_eyebrow_base.html component for heading
- Go to /photomatic-ai/ page and scroll to section "Photo Showcase", check by new design
QualityUnit/web-issues#3600
=> [3600] - photo showcase section

layouts/partials/sections/content/workflow-section.html, layouts/shortcodes/workflow-section.html
Added workflow section partial and shortcode
- Go to /affiliate-program-software/ page and check "How do Affiliate Programs work?" section by new design
QualityUnit/web-issues#3646
=> [3646] - added workflow section partial and shortcode

layouts/partials/sections/features/offset_with_feature_list.html, layouts/shortcodes/offset_feature_list.html
Enhancement to a partial to merge https://github.com/QualityUnit/FlowHunt-hugo/pull/172
=> feat: enhanced offset_feature list

layouts/partials/components/lists/with_icon.html, layouts/partials/sections/features/with_split_image.html, layouts/shortcodes/features-with-split-image.html
Updated features-with-split-image partial and with_icon partial (add svg support for icons)
- Go to /photomatic-ai/ page and check "Why Choose Photomatic" section
QualityUnit/web-issues#3586
=> [3586] - why choose photomatic fix

layouts/partials/sections/features/simple_three_column_with_large_icons.html
Adjusted padding for features-three-column section
- Go to /services/ai-small-businesses/ page and check padding for section "Our Small business Audit Plan"
QualityUnit/web-issues#3584
=> [3584] - fix: adjust padding for features-three-column section

layouts/partials/sections/content/three_columns_base.html
Updated card description font weight to normal
- Go to /photomatic-ai/ page and scroll to "You Dream It, Photomatic Creates It" section and check desription in cards
QualityUnit/web-issues#3600
=> [3600] - update card description font weight to normal

layouts/glossary/list.html, layouts/partials/hero_default.html, layouts/partials/sections/hero/simple_centered.html
Updated hero section padding and update glossary layout
- Go to /glossary/ list page and check hero section, should be by center
QualityUnit/web-issues#3459
=> [3459] - updated hero section padding and update glossary layout

assets/js/tooltips.js
we had in console error from tooltips. I fixed it
=> fix js for tooltips 

layouts/partials/sections/pricing/base.html, layouts/partials/sections/pricing/section.html, layouts/partials/sections/pricing/with_comparison_table.html
Added support for translation urls in buttons
=> added support for translation urls

assets/css/components/youtube-video.css, layouts/partials/sections/content/split_with_image.html
Fixed video element padding and play button
Close #[3645](https://github.com/QualityUnit/web-issues/issues/3645)
=> [3645] Fixed video element padding and play button

assets/css/main.css
fixed secondary classes for correct colors
=> fix secondary buttons on the dark bg

layouts/_default/_markup/render-link.html
- **🔗 Smart external link handling**: Automatically applies nofollow to external domains while preserving SEO benefits for QualityUnit domains
- **Out-of-box functionality**: Works without configuration with smart defaults
- **SEO optimized**: QualityUnit domains (liveagent.com, flowhunt.io, etc.) get SEO benefit without nofollow
- **Cost protection**: External domains get nofollow to prevent unwanted crawling costs
- **Auto-detection**: Current site domain automatically excluded from nofollow
- **Fully configurable**: Optional custom rules per domain in `params.toml`
- qualityunit.com, support.qualityunit.com
- liveagent.com, flowhunt.io, postaffiliatepro.com
- helpdesk.com, aimingle.cz, photomaticai.com, urlslab.com
```toml
[params.externalLinks]
nofollow = false  # Global disable …
```
=> Added external link handler

layouts/partials/helpers/generate-hreflang-links.html, layouts/partials/helpers/get-language-url.html, layouts/partials/helpers/load-translation-urls.html, scripts/translation-urls.py
Describe what was changed in the Pull Request
Describe how and what should be tested by a Tester
QualityUnit/web-issues#[ISSUE_NUMBER]
=> Alternate links bugs

assets/js/cookie-consent.js
added update captera  consent function
=> added captera to consent
